# Generated by Django 2.0.3 on 2018-03-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('display_level', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
                ('school', models.CharField(max_length=255)),
                ('ritual', models.BooleanField()),
                ('casting_time', models.CharField(max_length=255)),
                ('range', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('concentration', models.BooleanField()),
                ('verbal', models.BooleanField()),
                ('somatic', models.BooleanField()),
                ('materialistic', models.BooleanField()),
                ('materials', models.CharField(max_length=255)),
                ('bard', models.BooleanField()),
                ('cleric', models.BooleanField()),
                ('druid', models.BooleanField()),
                ('paladin', models.BooleanField()),
                ('ranger', models.BooleanField()),
                ('sorcerer', models.BooleanField()),
                ('warlock', models.BooleanField()),
                ('wizard', models.BooleanField()),
                ('description', models.TextField()),
            ],
        ),
    ]
